---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{R}
data = read.csv('activity.csv', colClasses=c('numeric', 'Date', 'numeric'))
head(data)
tail(data)
```


## What is mean total number of steps taken per day?

Per the assignment instructions, we will for now (naively) limit our analysis for this
problem to non-missing values:

```{R}
cleaned <- data[!is.na(data$steps),]
```

Find the total number of steps per day, excluding missing values:

```{R}
by_date <- split(cleaned, cleaned$date)
total_steps_per_day <- sapply(by_date, function (date) { sum(date$steps) })
```

Histogram of total steps per day:

```{R}
hist(total_steps_per_day, breaks=10, ylim = c(0, 25))
```

We can then calculate the mean and median number of steps taken per day as follows:

```{R}
mean(total_steps_per_day)
median(total_steps_per_day)
```


## What is the average daily activity pattern?

To find the average number of steps per 5-minute interval across all days, we split the
cleaned dataset (i.e., still ignoring NAs) across the interval numbers:

```{R}
by_interval = split(cleaned, cleaned$interval)
averages <- sapply(by_interval, function (interval) { mean(interval$steps) })
plot(x = unique(cleaned$interval),
     y = averages,
     type = 'l',
     xlab='Time of day',
     ylab='Average steps taken')
```

We can figure out which of these 5-minute intervals, averaged across days, contained the
most steps as follows:

```{R}
averages <- data.frame(interval = names(averages), average_steps=averages)
library(dplyr)
tail(arrange(averages, average_steps))
```

As we can see from the sorted data frame, interval 835 had the highest average number of
steps across all days.


## Imputing missing values

The number of rows (measurement intervals) missing data can be found as follows:

```{R}
sum(is.na(data$steps))
```

As a way to estimate these missing data values, we will use the average values for the
5-minute intervals as calculated earlier in this assignment.

A dataset which "fills in" these missing values using this strategy can be constructed as
follows:

```{R}
interpolated <- data
for(i in 1:nrow(data)) {
  if(is.na(data$steps[i])) {
    interval <- data$interval[i]
    estimated_steps <- averages$average_steps[averages$interval == interval]
    interpolated$steps[i] <- estimated_steps
  }
}
```

Now we can recalculate the total number of steps taken per day and do a new histogram:

```{R}
by_date <- split(interpolated, interpolated$date)
total_steps_per_day <- sapply(by_date, function (date) { sum(date$steps) })
hist(total_steps_per_day, breaks=10, ylim = c(0, 25))

```

And we can calculate the mean and median of the new dataset as follows:

```{R}
mean(total_steps_per_day)
median(total_steps_per_day)
```

It is notable that the means of both these calculations are identical, while the medians
differ only slightly (the median matching the mean exactly in the latter calculation).

This ultimately makes sense; as the code below reveals, all of the dates sampled in this
study either featured a complete set of data for all intervals, or else all NAs:

```{R}
by_date <- split(data, data$date)
percent_na_by_date <- sapply(by_date, function (date) {
  sum(is.na(date$steps)) / nrow(date)
})
print(percent_na_by_date)
```

What this means is that when we impute the mean number of steps per interval to each of
these 100% NA days, we essentially add several new samples to our data set with a total
number of steps per day lying exactly at the previously calculated dataset mean.

Thus, it's not surprising that our mean total steps per day remains unchanged, and that
we end up with a sufficient number of samples perfectly at the mean to forcibly shift
the median to be equal to the mean.


## Are there differences in activity patterns between weekdays and weekends?

First we add a column to our data frame to identify whether each sample took place on a
weekday or weekend:

```{R}
interpolated$day_type <- factor(sapply(interpolated$date, function (date) {
  weekday <- weekdays(date)
  if(weekday %in% c('Saturday', 'Sunday')) {
    'weekend'
  } else {
    'weekday'
  }
}))
```

First, we separate out our weekday and weekend recordings into separate datasets:

```{R}
is_weekday <- function (date) {
  weekdays(date) %in% c('Saturday', 'Sunday')
}
weekday_data = interpolated[is_weekday(interpolated$date),]
weekend_data = interpolated[!is_weekday(interpolated$date),]
```

Get the average number of steps for each dataset separately:

```{R}
average_steps_by_interval <- function (dataset) {
  by_interval <- split(dataset, dataset$interval)
  sapply(by_interval, function (interval) { mean(interval$steps) })
}

weekdays <- average_steps_by_interval(weekday_data)
weekends <- average_steps_by_interval(weekend_data)
```

Combine these two into a data frame, identifying which are weekdays, which weekends:

```{R}
weekdays <- data.frame(
  interval=as.numeric(names(weekdays)),
  steps=weekdays,
  day_type=rep('weekday', length(weekdays)))
weekends <- data.frame(
  interval=as.numeric(names(weekends)),
  steps=weekends,
  day_type=rep('weekend', length(weekends)))

averages <- rbind(weekdays, weekends)
averages$day_type <-factor(averages$day_type, levels=c('weekday', 'weekend'))
averages <- arrange(averages, interval)
head(averages)
```

Now we can do a side-by-side time series plot of the average number of steps taken per 5-minute interval on weekdays vs. weekend days:

```{R}
library(lattice)
xyplot(
  averages$steps ~ averages$interval | averages$day_type,
  type = 'l',
  layout = c(1, 2))


xyplot(
  average_steps_by_interval(interpolated)~unique(interpolated$interval)|interpolated$day_type,
  type = 'l',
  layout = c(1, 2),
  xlab = 'Interval',
  ylab = 'Number of steps')
```